### ISSUE TITLE
出社/在宅について

### ISSUE THREAD

**Issue by go-sato555** [imobile/AP-sales#19]
↓↓↓↓下記松山さんから↓↓↓↓
今日のwevoxでリモートについての発言がいくつか社長とかオーテとかからもあったけど、
昨日の櫻井の提案に関して、マネージャーの席決めをするMTGの際に、
他のMGRの意見なども聞いてみてくれない？一人の意見で上げるのはさすがに無理なので。

▼俺の理解している櫻井の提案
①週一在宅を許可し、それ以外の在宅は理由関係なしに有給取得とする。
②猛暑の日（最高気温35度以上）は在宅をしてもよい。
③半休の日は、在宅をしてもよい。

▼ケアすべき部分（俺が気になる点も含む）
・上記の特に①は本当に皆がそう思っているか？を確認。（現場も含め）
　└俺の意見は参考にしなくてもいいけど、俺の場合は①は微妙と思った。
　　└理由は「子供の体調不良が1日で治るわけではないから」で、
　　　有給は余っているけど、そのたびに有給消化していたら自分の体調不良の際に
　　　ぎりぎりになっているとか嫌だなって思ったりしました。

・②は経理や管理部などバックオフィスは皆出社が必須なので、猛暑関係なく出社が必要であるということ。

この中なら伝え方によっては③はどうにかなるんじゃないか？と思っている部分はある。

とりあえず、MGR同士で話してみてほしいです。

_Originally posted by @go-sato555 in https://github.com/imobile/AP-sales/discussions/18_

**Comment by misa-sakurai** [comment]
①体調不良の在宅どうする？
・家庭の事情だったら日数は設けない
　∟事前相談（要相談）
・体調不良だったら週1まで在宅OK（基本はその在宅を使わない）

➁半休とったとき出社ではなく在宅でいいのでは？
・移動時間分で仕事ができる。
　∟業務効率化

**Comment by go-sato555** [comment]
[info]    ポイント1：在宅勤務（テレワーク・在宅ワーク・リモートワーク）を認める条件を決める。
    ポイント2：在宅勤務（テレワーク・在宅ワーク・リモートワーク）を認める期間を決める。
    ポイント3：就業時間に関するルールを決める。
    ポイント4：就業場所に関するルールを決める。
    ポイント5：業務上の情報の取扱いのルールを決める。
    ポイント6：在宅勤務（テレワーク・在宅ワーク・リモートワーク）中の費用負担に関するルールを決める。
    ポイント7：在宅勤務（テレワーク・在宅ワーク・リモートワーク）中の手当支給に関するルールを決める。[/info]

**Comment by atsu-taga** [comment]
7/28
・体調不良の在宅はNGで、基本有給を取得する
・半休取得した際は、残りの半日は在宅しても出社してもOK
┗許可制ではなく、報告制でOK
・コロナ/インフルエンザ/怪我等の外的要因の場合は、
　コロナ/インフルは5日間基本有休を取得する。しかし、回復したタイミングで上長に相談し在宅を許可する。

**Comment by atsu-taga** [comment]
**最終決定**
▼在宅許可を検討する場合
・家庭の事情による内容（親の介護、子の看護、その他センシティブな内容等）
　└センシティブな内容の場合、全体の板で投稿する前に上長に直接相談してください。

▼在宅を許可しない事項
・体調不良
　└体調不良は有給を取得してください。

▼その他
・半休の場合、残りの勤務時間は在宅を許可する
（例）午前半休を取得した場合、午後の出勤は在宅をしても良い。逆も然り。

・コロナ/インフルエンザ/怪我等の外的要因の場合
　└コロナ/インフルは原則5日間基本有休を取得する。
　　回復したタイミングで上長に相談し在宅の許可を相談する。
　　怪我の場合は怪我の状況や容体などを上長と定期的に相談したうえで、
　　必要な在宅期間を確定させる。
